### ISSUE TITLE
Plugins with options?

### ISSUE THREAD

**Issue by bcomnes** [stackcss/sheetify-postcss#1]
Does this support passing options to plugins?

**Comment by ahdinosaur** [comment]
hey @bcomnes. oh, i guess not. if you contribute a pull request to implement this i'll be happy to merge and publish. :smile:

**Comment by bcomnes** [comment]
Maybe if I have time.  Closing for now.  I'll reopen if I start on it.  Anyone else feel free to take a stab in the meantime.

**Comment by bcomnes** [comment]
What I did discover is that you can pass options to the post-css transform like: https://github.com/hypermodules/hyperamp/blob/master/package.json#L64
